log "Workstation Cookbook Linked Recipie Activated"

include_recipe "pivotal_workstation::bash_profile-better_history"
include_recipe "pivotal_workstation::bash_path_order"
include_recipe "pivotal_workstation::bash_profile"
include_recipe "pivotal_workstation::finder_display_full_path"
include_recipe "pivotal_workstation::git_config_global_defaults"
include_recipe "pivotal_workstation::inputrc"
include_recipe "pivotal_workstation::osx_turn_on_locate"
include_recipe "pivotal_workstation::textmate_set_defaults"
include_recipe "pivotal_workstation::rvm"
include_recipe "pivotal_workstation::mysql"
include_recipe "pivotal_workstation::defaults_fast_key_repeat_rate"
include_recipe "pivotal_workstation::ssh_copy_id"
include_recipe "pivotal_workstation::ec2_api_tools"